### ISSUE TITLE
move to koopjs org

### ISSUE THREAD

**Issue by ungoldman** [koopjs/koop-pgcache#13]
@chelm can we move this to the koopjs org?

**Comment by chelm** [comment]
@ngoldman I can, i'll need a gh admin to grant me ownership first

**Comment by chelm** [comment]
or @ajturner can move it to the koopjs org and save me from bothering the gh admins with small things...

**Comment by chelm** [comment]
@ajturner++

**Comment by ungoldman** [comment]
thanks! I'll update package.json info with the new address

**Comment by chelm** [comment]
@ngoldman ahh, yes, very nice indeed
